### PR TITLE
[Bigtable] Remove unnecessary async/await

### PR DESCRIPTION
**Pull request by evildour**

### CODE REVIEW

**Comment by evildour** [comment]
It might. How would that cause a difference though? It was being awaited here and then the caller was awaiting `EstablishStream`. How would it be different if just the latter were taking place?

**Comment by jskeet** [comment]
(On a phone now, so can't check the code) It's the difference between the method throwing directly or returning a faulted task. It may not matter here - can't tell right now.

**Comment by evildour** [comment]
I don't think it will matter since both callers await it immediately anyway, so either the throw would occur here or at the call site.

**Comment by jskeet** [comment]
Makes sense. May affect the stack trace but that's all.

**Comment by evildour** [comment]
Right, thanks

**Pull request merged**
