### PR TITLE
Metadata library docs

### PR DESCRIPTION
**Pull request by evildour**
Sample code/snippets to be added later (when #412 is merged)

### CODE REVIEW

**Comment by jskeet** [comment]
Do you want a review on this now, or is there more to come?

**Comment by evildour** [comment]
Oh sorry, yes that would be in a separate PR. Please review now. Thanks.

**Comment by evildour** [comment]
I can add it to index.md. Should we wait until the implementation is merged though, or does it not matter?

**Comment by jskeet** [comment]
Happy for you to include it in any PR you want - it won't make any difference until I manually regenerate the docs anyway.

**Comment by evildour** [comment]
Ok, added in #435

**Pull request merged**
