### PR TITLE
Fix Bigtable generation

### LINKED ISSUE #2422: Update Bigtable code generator
Since updating to Visual Studio 15.8, the VS code generator isn't working for me. I suspect we need a later set of Roslyn dependencies. Will investigate.

### PR DESCRIPTION
**Pull request by jskeet**
Fixes #2422.

### CODE REVIEW

**Comment by amanda-tarafa** [comment]
The last commit makes the build fail.

**Comment by jskeet** [comment]
Urgh - thanks, will look when I can. (Currently drowning in smallish tasks...)

**Comment by jskeet** [comment]
Looks like updating the SDK version may fix this. Will need to check that doesn't break Kokoro as well though.

**Comment by jskeet** [comment]
(Will fix Kokoro if it breaks :)

**Comment by evildour** [comment]
Sorry, just saw this now.

**Pull request merged**
