### PR TITLE
Add an example of using the IManagedTracer in AspNetCore with MVC

### LINKED ISSUE #948: System.InvalidOperationException : Could not create an instance of type 'Google.Cloud.Diagnostics.Common.IManagedTracer'. Model bound complex types must not be abstract or value types and must have a parameterless constructor.
Hi,

using .net core 1.1, and package  `<PackageReference Include="Google.Cloud.Diagnostics.AspNetCore" Version="1.0.0-alpha07" />`

```
Mac:UDL-API$ dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 `Version:`            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```

i get the error 
' System.InvalidOperationException : Could not create an instance of type 'Google.Cloud.Diagnostics.Common.IManagedTracer'. Model bound complex types must not be abstract or value types and must have a parameterless constructor.'

- startup.Configure() contains app.UseGoogleTrace()
- startup.ConfigureServices() contains services.AddGoogleTrace(Configuration["AppSettings:GoogleProjectID"]);
- my post http controller contains tracer.StartSpan(nameof(GetWellData)); (& endspan()).

That may be an issue on my side, but the documentation at http://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNetCore/  does not really give much more clue on what is going on.

### PR DESCRIPTION
**Pull request by iantalarico**
The usage is not straight forward as an extra attribute is required to inject the IManagedTracer into MVC action methods.

Fixes #948

### CODE REVIEW

**Comment by iantalarico** [comment]
I think everything needed was pushed in alpha 7 in early March.  I'm happy to just push this out with a new release if that's easier/safer too.

**Comment by jskeet** [comment]
I'm in the middle of huge updates in prep for a release anyway, so it should be fine.

**Comment by iantalarico** [comment]
@jskeet actually you are correct, given the #951 the docs are ahead of the code :(

**Comment by evildour** [comment]
LGTM

**Pull request merged**
