### PR TITLE
Merge Spanner work into master

### PR DESCRIPTION
**Pull request by jskeet**
I tried to clean this up, but it's too tricky as it was merged with master part way through - it doesn't rebase cleanly, and I don't want to lose information.

Ben, once it's green, if you could run the integration tests, that would be useful.

### CODE REVIEW

**Comment by benwulfe** [comment]
Looks like some changes were missed so I redid the master rebase using some git magic and all tests are passing on my PR here: 
https://github.com/GoogleCloudPlatform/google-cloud-dotnet/pull/1113

looks like an appveyor issue -- but build works as do all my tests -- so I think its quite close.

**Comment by jskeet** [comment]
Have taken your PR, added one commit, and that's what this is now. Will run your tests, and merge on green.

**Comment by jskeet** [comment]
Tests pass, CI is green... merging!

**Comment by jskeet** [comment]
Restored the branch so the Spanner team can fetch it for review.

**Pull request merged**
