### PR TITLE
Regenerate all APIs

### PR DESCRIPTION
**Pull request by jskeet**
As far as I can see, the changes are only:

- Copyright dates
- Lack of _clientHelper field
- Snippets populating requests

### CODE REVIEW

**Comment by chrisdunelm** [comment]
Is the error due to #730 not yet being implemented?
Although it looks like it may be worth passing the clientHelper to OnConstruction.
I can put #730 in the codegen today if required.

**Comment by jskeet** [comment]
Whoops, I hadn't seen that there was an error.

Urgh - yes, implementing #730 would fix that, and yes, passing in the client helper would probably be the best approach, to avoid the duplicate logic.

**Comment by chrisdunelm** [comment]
OK, PR coming soon...

**Comment by chrisdunelm** [comment]
https://github.com/googleapis/toolkit/pull/1044

**Comment by jskeet** [comment]
Right, should be fixed now... let's see if it goes green :)

**Comment by chrisdunelm** [comment]
Green :) I'll take a look now.

**Pull request merged**
