### PR TITLE
[DO NOT MERGE] Prototype of Translation v2 (breaking change for models)

### PR DESCRIPTION
**Pull request by jskeet**
This treats models as simple strings. No validation is performed.
Everything defaults to null, meaning "don't specify any model".
If a model is specified as the default for a client, then a null
argument in a method call means "use the default" but an empty string
means "wipe out the default; don't send any model in the request."

All of this is a breaking change, hence the major version bump.
We don't know if we want to do this - this PR is intended to help
the conversation.

### CODE REVIEW

**Comment by evildour** [comment]
Would it make sense to have a class with string constants for which models are currently known?

**Comment by jskeet** [comment]
The Translation team has suggested they'd prefer not to do that.

**Comment by evildour** [comment]
Oh, interesting. So using this library, how would I know what string to pass in? I guess in that case I probably would just not specify it.

**Comment by jskeet** [comment]
Yes - basically it would be a case of looking at the docs, and if you have early access to some models, you'd already know about them.

**Comment by evildour** [comment]
I see, makes sense.

**Comment by jskeet** [comment]
(We're going in the alternative direction - closing this PR.)

**Pull request closed without merging**
