### PR TITLE
Fixed some warnings in Clouderrorreporting

### PR DESCRIPTION
**Pull request by evildour**
(it looks like these were changed as part of an [auto-generation commit](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/pull/512/commits/ed19f7e8a8d47fb5833b6e4616cac4b3fff1583c), but this doesn't look like an auto-generated file, so I'm not sure if its correct to hand edit these)

### CODE REVIEW

**Comment by jskeet** [comment]
Nope, this is an autogenerated file - the fact that it doesn't look that way is testament to @chrisdunelm's hard work :)

I suggest we leave it as it is for now, but Chris takes it as another item to fix... basically removing the `@` in XML doc comments. (It's required for the variable name itself as it's a keyword.)

**Comment by evildour** [comment]
Ok, I'll close the PR then. I'm curious though: where is the code which auto-generates this? I searched for a while for various things which I thought might be in the auto-generation logic but couldn't find it. Funny though: I spent all this time looking for the auto-generation logic and I missed the `// Generated code. DO NOT EDIT!` note at the top of the file!

**Comment by jskeet** [comment]
It's generated by https://github.com/googleapis/toolkit

**Comment by evildour** [comment]
Great, thanks!

**Pull request closed without merging**
