### PR TITLE
Reuse trace test servers when possible and fix flakiness of Trace_QPS .

### PR DESCRIPTION
**Pull request by iantalarico**
- Reuses trace test servers when possible.
- Change the logic in Trace_QPS to be more robust.

These changes will reduce test run time and fix some test flakiness.

### CODE REVIEW

**Comment by evildour** [comment]
You may need to rebase master. AppVeyor has an error that the UploadObjectWithSessionUri snippet can't be found, which I just added in #890.

**Comment by iantalarico** [comment]
@evildour I'm already merged with the latest bits, I'll take a closer look.

**Comment by iantalarico** [comment]
@evildour it looks like this failure started in #890.  Although looking at the PR I'm not sure why.  It looks correct.

**Comment by iantalarico** [comment]
@jskeet @evildour  Getting off topic but I tried to build the docs locally but wasn't quite sure what to do.  Do we have something to generate docfx.jsons?

**Comment by evildour** [comment]
I haven't tried building them locally, but I think I see what the problem is. About to submit a PR and will merge if it fixes the issue.

**Comment by iantalarico** [comment]
I don't think we will run into interdependence if we reuse the server as long as we clean the work space up.  However, I also don't see a reason to reuse them if we don't have too.

**Pull request merged**
