### PR TITLE
[Bigtable] Cap multi-channel support to using 2 channels during testing.

### PR DESCRIPTION
**Pull request by evildour**
(each integration test was taking ~5 seconds for me instead of a few milliseconds after #1954)

### CODE REVIEW

**Comment by jskeet** [comment]
I'm somewhat concerned that this is necessary - does it suggest that #1954 will bite regular users too? I didn't review that PR before, would you like me to have a look now?

**Comment by evildour** [comment]
Yeah that might be a good idea. I guess I didn't realize how much overhead was involved in an initial call over a channel. With many cores, each test uses a few new channels that have never been used before and it slows down those initial tests. In a normal application, I assume this is ok for application startup, but wouldn't be a problem if the same client is used throughout (so we're probably going to need good docs around that as well).

**Comment by evildour** [comment]
BTW, do we make a similar recommendation anywhere with `PublisherClient`? I imagine that would have a similar issue as it too uses multiple new channels by default.

**Comment by jskeet** [comment]
@chrisdunelm would know more about PublisherClient than I can remember.

There are additional issues with using explicitly-provided channels, in that we should clean them up if possible - see #1966 for example. This whole area probably needs more thought.

Friday afternoon probably isn't the best time for me to think about this, so I'll punt it to Monday and look closely then. I'm happy for us to merge this for now if you think that's a good idea though.

**Comment by chrisdunelm** [comment]
This hasn't been an issue with Pubsub integration tests. However, they are all fairly long-running tests (> 1 minute each), so a few seconds extra for channel creation wouldn't be noticeable.
Next week I may do a test that does nothing, just to see the time taken for channel setup.

**Comment by evildour** [comment]
As far as cleanup goes, #1973 will eventually address that, but I need to sync up with Alex about it next week.

**Comment by evildour** [comment]
Closing: we're going to go with a different approach for channel pooling, so this probably won't apply after that.

**Pull request closed without merging**
