### PR TITLE
(Not for submission) WinForms speech demo

### PR DESCRIPTION
**Pull request by jskeet**
This uses NAudio for speech input.

@chrisdunelm  @SurferJeffAtGoogle @evildour for potential interest.

### CODE REVIEW

**Comment by SurferJeffAtGoogle** [comment]
Thanks.  I'd love to use this demo during my upcoming talks.

I downloaded the code, opened the project, and got a couple warnings.  Then, the build failed.  When I saw this build error before in another app, I was able to edit the Web.config to fix it.  But I haven't figured out the project.json well enough to fix it here.  And why doesn't System.Runtime appear in the list of assemblies in the "Add Reference" dialog?

system runtime

**Comment by jskeet** [comment]
@SurferJeffAtGoogle: Given the red squiggles under `netstandard1.3`, my guess is that you don't have .NET Core installed, or possibly just not the latest VS2015 tooling for it. There was a hotfix to VS2015 update 3 recently around the .NET Core tooling, too. (It's not running under .NET Core, but an msbuild-based project can't depend on a dotnet-cli-based project within a solution, which is why even the WInForms project is dotnet-cli.)

**Comment by SurferJeffAtGoogle** [comment]
dnx sdk version warning
It looks like the project is using an older version of the SDK than I have.

**Comment by SurferJeffAtGoogle** [comment]
dns failed to install
And when I click Yes to install, it fails.

**Comment by jskeet** [comment]
That's talking about DNX, which predates dotnet cli. If you run `dotnet --info` from the command line, what do you see?

**Comment by jskeet** [comment]
Basically, to get the .NET Core SDK, go to https://www.microsoft.com/net/core#windows

**Comment by SurferJeffAtGoogle** [comment]
I installed everything on that page.  I still get the same error.  See
attached video.

**Comment by jskeet** [comment]
Could you check what's in `c:\Program Files\dotnet\sdk`? I suspect that you may have a `1.0.0-preview2-003131` directory but no `1.0.0-preview2-003121` directory - in which case it's simple to fix. (preview2-003131 came out at the end of August, by the looks of it.) It should be a matter of just updating all the projects to the newer version.

I'll wait until you've confirmed that you have got that directory first though :)

**Comment by SurferJeffAtGoogle** [comment]
PS C:\Program Files\dotnet\sdk> ls


    Directory: C:\Program Files\dotnet\sdk


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        9/26/2016   4:20 PM                1.0.0-preview2-003131


PS C:\Program Files\dotnet\sdk>

**Comment by jskeet** [comment]
Excellent. That should be a simple matter to fix then. Will do that in a separate PR, then rebase this one...

**Comment by jskeet** [comment]
Rebased to include the commit updating to 003131, so if you pull now (with forcing) it *should* be okay. Fingers crossed...

**Comment by evildour** [comment]
I'm able to get this working on my machine but each time it will record a few sentences and then appear to stop. When this happens, I see an exception, but only when I hit the stop button. Unfortunately it doesn't contain much detail:

```
Grpc.Core.RpcException was unhandled by user code
  HResult=-2146233088
  Message=Status(StatusCode=Unknown, Detail="")
  Source=mscorlib
  StackTrace:
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Grpc.Core.Internal.ClientResponseStream`2.<MoveNext>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Google.Cloud.Speech.V1Beta1.WinFormsRecognizer.Recognizer.<ConsumeResultsAsync>d__10.MoveNext() in C:\Users\miked\Documents\git_projects\google-cloud-dotnet\apis\Google.Cloud.Speech.V1Beta1\Google.Cloud.Speech.V1Beta1.WinFormsRecognizer\Recognizer.cs:line 78
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Google.Cloud.Speech.V1Beta1.WinFormsRecognizer.SpeechDemoForm.<StartOrStop>d__2.MoveNext() in C:\Users\miked\Documents\git_projects\google-cloud-dotnet\apis\Google.Cloud.Speech.V1Beta1\Google.Cloud.Speech.V1Beta1.WinFormsRecognizer\SpeechDemo.cs:line 51
  InnerException: 
```

I did get one helpful message when something else on my machine happened to be using a lot of the CPU:

```
Grpc.Core.RpcException was unhandled by user code
  HResult=-2146233088
  Message=Status(StatusCode=OutOfRange, Detail="Audio data is being streamed too slow. Please stream audio data approximately at real time.")
  Source=mscorlib
  StackTrace:
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Grpc.Core.Internal.ClientResponseStream`2.<MoveNext>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Google.Cloud.Speech.V1Beta1.WinFormsRecognizer.Recognizer.<ConsumeResultsAsync>d__10.MoveNext() in C:\Users\miked\Documents\git_projects\google-cloud-dotnet\apis\Google.Cloud.Speech.V1Beta1\Google.Cloud.Speech.V1Beta1.WinFormsRecognizer\Recognizer.cs:line 78
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Google.Cloud.Speech.V1Beta1.WinFormsRecognizer.SpeechDemoForm.<StartOrStop>d__2.MoveNext() in C:\Users\miked\Documents\git_projects\google-cloud-dotnet\apis\Google.Cloud.Speech.V1Beta1\Google.Cloud.Speech.V1Beta1.WinFormsRecognizer\SpeechDemo.cs:line 51
  InnerException: 
```

But again, I needed to hit the stop button to actually see the exception. I think it would be better if this could detect and throw exceptions as they occur. However, I didn't look into it too much. This might be something on the API end and there's not much the library or sample can do here.

**Comment by jskeet** [comment]
The first one seems very odd. The business about not seeing anything until you stop is due to the current code effectively "losing" the task used to post intermediate requests. This is all still rough and ready :) We can definitely improve how the error is reported, but I don't know why you'd get the error to start with...

**Comment by evildour** [comment]
Ok so I used GRPC_TRACE and unfortunately didn't learn much yet from the output yet, but I did get an error message with a bit more info. I'm not sure its the same error because it happened a while after hitting stop while I was reading through the output (and perhaps it only occurred because the env. variable was set).

```
Grpc.Core.RpcException occurred
  HResult=-2146233088
  Message=Status(StatusCode=Unavailable, Detail="{"created":"@1475282974.915000000","description":"Secure read failed","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\csharp\platform\windows\vsprojects\..\src\core\lib\security\transport\secure_endpoint.c","file_line":157,"grpc_status":14,"referenced_errors":[{"created":"@1475282974.915000000","description":"End of TCP stream","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x64\language\csharp\platform\windows\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":180}]}")
  Source=mscorlib
  StackTrace:
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Grpc.Core.Internal.ClientResponseStream`2.<MoveNext>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Google.Cloud.Speech.V1Beta1.WinFormsRecognizer.Recognizer.<ConsumeResultsAsync>d__10.MoveNext() in C:\Users\miked\Documents\git_projects\google-cloud-dotnet\apis\Google.Cloud.Speech.V1Beta1\Google.Cloud.Speech.V1Beta1.WinFormsRecognizer\Recognizer.cs:line 78
  InnerException: 
```

The Detail prettified looks like this:
```
{
  "created": "@1475282974.915000000",
  "description": "Secure read failed",
  "file": "c:\\jenkins\\workspace\\gRPC_build_artifacts\\architecture\\x64\\language\\csharp\\platform\\windows\\vsprojects\\..\\src\\core\\lib\\security\\transport\\secure_endpoint.c",
  "file_line": 157,
  "grpc_status": 14,
  "referenced_errors": [
    {
      "created": "@1475282974.915000000",
      "description": "End of TCP stream",
      "file": "c:\\jenkins\\workspace\\gRPC_build_artifacts\\architecture\\x64\\language\\csharp\\platform\\windows\\vsprojects\\..\\src\\core\\lib\\iomgr\\tcp_windows.c",
      "file_line": 180
    }
  ]
}
```

It looks like its similar to (or the same as) this issue: https://github.com/grpc/grpc/issues/7804

**Comment by evildour** [comment]
I got a chance to try this again and I think I'm able to reproduce the error I was seeing before, but now there is actually a helpful message in the RpcException:
```Status(StatusCode=OutOfRange, Detail="Exceeded maximum allowed stream duration of 65 seconds.")```

**Comment by jskeet** [comment]
Excellent - I've failed to reproduce that specific error so far, but I'm still experimenting. (We're actively working on the streaming at the moment.)

Did you see the exception in the *response*, or as a failure to *write*?

**Comment by evildour** [comment]
The response. Usually I don't see the error until hitting the stop button and then an exception occurs in `ConsumeResultsAsync` on the line which says `while (await responses.MoveNext())` with this stack trace:

```
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.ClientResponseStream`2.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Google.Cloud.Speech.V1Beta1.WinFormsRecognizer.Recognizer.<ConsumeResultsAsync>d__10.MoveNext() in C:\Users\miked\Documents\git_projects\google-cloud-dotnet\apis\Google.Cloud.Speech.V1Beta1\Google.Cloud.Speech.V1Beta1.WinFormsRecognizer\Recognizer.cs:line 81
```

However, I also occasionally see the `response.Error` value set in an iteration of the while loop, with that value's debugger visualization saying "{{ "code": 11, "message": "Exceeded maximum allowed stream duration of 65 seconds." }}"

I'm able to reproduce the issue pretty consistently by just using the sample for 65 seconds.

**Comment by jskeet** [comment]
This is now obsolete - closing.

**Pull request closed without merging**
