### PR TITLE
 Add remaining Bigtable helpers

### PR DESCRIPTION
**Pull request by evildour**
Recommend to review one commit at a time.

### CODE REVIEW

**Comment by jskeet** [comment]
@chrisdunelm Are you okay to review this? It's a bit much to review while on vacation :)

**Comment by chrisdunelm** [comment]
Yes, I'll review it. It'll probably be tomorrow though.

**Comment by evildour** [comment]
Sorry Jon, didn't realize you were on vacation. Thanks Chris!

**Comment by evildour** [comment]
Thanks Chris! We're still in alpha, so not much harm in making changes after the fact anyway if Jon (or anyone else) notices any issues.

**Pull request merged**
