### PR TITLE
Regenerate all APIs

### PR DESCRIPTION
**Pull request by jskeet**
I've tried to break these up into sensible commits; I'd suggest reviewing one commit at a time

### CODE REVIEW

**Comment by jskeet** [comment]
cc @evildour: Note the server streaming Bigtable calls :)

**Comment by chrisdunelm** [comment]
Looks like you need to run generateprojects.sh

**Comment by jskeet** [comment]
Humbug. Was hoping to avoid that - can't do it on the same machine. (I manually changed the Datastore version number.)

Righto, will fetch and add a commit...

**Comment by jskeet** [comment]
Ah - and of course I fouled it up doing it manually, but I can fix it up manually too. Looks like that's the only issue.

**Comment by jskeet** [comment]
Merging myself, as it looks okay.

**Pull request merged**
