### PR TITLE
Update to .NET Core SDK 2.1.400

### LINKED ISSUE #2430: dotnet sln add broken in our project generation
I've just generated a new API, and the solution file is empty. Running `dotnet sln add path/to/csproj` I get an error message of:

> Project '...Project.csproj' has an unknown project type and cannot be added to the solution file. Please contact your SDK provider for support.

I suspect this is related to the VS15.8 update...

### PR DESCRIPTION
**Pull request by jskeet**
This allows "dotnet sln add" to work.

Fixes #2430.

I propose that we merge if this is green for Travis and AppVeyor. We may then need to update Kokoro.

### CODE REVIEW

**Comment by iantalarico** [comment]
@jskeet Looks like AppVeyor and Travis aren't updated yet.  Maybe this is a good time to try and migrate all the CI/CD to Kokoro?

**Comment by jskeet** [comment]
Travis we should be able to fix ourselves - I just failed to do so. AppVeyor we have less control over. Would like to keep at least Travis going, but don't mind losing AppVeyor, at least temporarily.

**Comment by iantalarico** [comment]
Okay, let's sync up when you are back in the office next week and discuss further.

**Comment by jskeet** [comment]
Okay, it looks like AppVeyor now supports 2.1.400.

Ian, Chris - are you both happy for us to merge this and then update Kokoro if necessary?

**Comment by jskeet** [comment]
Merging now, which may well break Kokoro - but we need to find out at some point anyway.
(This bit me yet again today...)

**Pull request merged**
