### PR TITLE
Add NLog to top-level doc

### PR DESCRIPTION
**Pull request by chrisdunelm**

### CODE REVIEW

**Comment by chrisdunelm** [comment]
Only commit after the http://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Logging.NLog/ is working.

**Comment by jskeet** [comment]
That page is now working, so we can merge this.

**Comment by chrisdunelm** [comment]
Thanks, I'd forgotten about this ;) Merging.

**Comment by jskeet** [comment]
Given that I'm doing loads of doc pushing at the moment (from when CI was broken) I'll repush the root doc with this in too.

**Pull request merged**
