### PR TITLE
Move DevTools.Common to GA

### PR DESCRIPTION
**Pull request by chrisdunelm**

### CODE REVIEW

**Comment by chrisdunelm** [comment]
Looks like we can move this to GA now. @Deren-Liao Is there any reason not to do this?

**Comment by jskeet** [comment]
There are no tests at the moment, as indicated by #988.

**Comment by Deren-Liao** [comment]
Hi Chris,

Go ahead. Thanks for taking care of this.  I'll try to add tests in this
quarter.

-Deren

**Comment by jskeet** [comment]
I really don't think we should go GA without a single test. Let's have a look over the code and see what might benefit most.

**Comment by Deren-Liao** [comment]
I'll add as soon as possible.

**Comment by Deren-Liao** [comment]
Hi Jon, Chris,

Sorry for the delay.  I did not get that Jon meant to ask me to add tests immediately.  I created a pull request with some unit tests.  Please check.

**Comment by Deren-Liao** [comment]
I've updated the version number . You can close the PR now.

**Comment by jskeet** [comment]
Closing this in favour of #1297.

**Pull request closed without merging**
