### PR TITLE
Use Roslyn v2 for analyzers

### PR DESCRIPTION
**Pull request by jskeet**
Tested by including failing code, and then removing that commit. This way we get analyzers in CI...

### CODE REVIEW

**Comment by jskeet** [comment]
We have to target Roslyn 2.0 as that's the version that the dotnet CLI we're using also uses. Trying again...

**Comment by jskeet** [comment]
(Using the publish directory may well help in terms of being able to rebuild the tools solution with VS open, btw. It was originally to get around a different problem, but that's a side benefit.)

**Comment by evildour** [comment]
How would the normal development process work now? Using the publish directory means just building the tools solution now is no longer sufficient to get the analyzers to be used when working in one of the projects. Do we have to remember to publish the appropriate build if we want to use them locally?

**Comment by jskeet** [comment]
Yes, I think so - which we can easily put in a shell script, of course. But if we don't update them very often, it's a mostly "one off" build...

**Comment by evildour** [comment]
Ok, yeah I guess if anyone does forget and something slips through, at least the CI build should catch it. Also, I tried using these changes to see if I could go back to including the analyzers in each solution with build dependencies, but the issue about 'dotnet build' assuming build dependencies are project dependencies still occurs, but now it is the net45 target which can't build because it is 'depending' on the netstandard1.3 analyzers.

LGTM.

**Comment by jskeet** [comment]
Thanks for that. I'm definitely keener on the CI catching things but devs maybe not than the other way round...

**Comment by evildour** [comment]
Had another thought about this: we could have the project generator create two analyzer nodes pointing to the same dll - one conditioned on the release build and pointing to the publish dir and the other conditioned on the debug build not pointing to the publish dir. Once the build dependency issue is sorted out, then I think things could work well for both scenarios.

**Comment by jskeet** [comment]
We could do that... but I fear we'll get into the locking situation again. Let's see how we go. I might ask the Roslyn team if they have any recommendations for this sort of thing...

**Comment by evildour** [comment]
What was the locking situation? I don't think I saw any issues with VS open.

**Comment by jskeet** [comment]
I thought you had to reboot because VS had something locked while a build was trying to replace it, or similar?

**Comment by evildour** [comment]
Oh right. I don't remember exactly what the issue was because I was dealing with a lot of various problems there, but for that I do remember two things about that issue: 1) it was happening during a command line build and 2) a reboot didn't help. I think some other error in the build and/or running analyzers process earlier was causing files to get locked later.

**Pull request merged**
